services:
  bot:
    container_name: bot_prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always
