FROM python:3.12.4-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && \
    apt-get install -y \
    nodejs \
    ffmpeg \
    npm && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

FROM base AS final

WORKDIR /app

COPY ./ /app

CMD ["python", "-u", "main.py"]